// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7VC7Z9oCbt8y3virEqPsovvjzNvaXlXk',
    appId: '1:843619339586:web:356211a15712ff1b0b4cdb',
    messagingSenderId: '843619339586',
    projectId: 'auth--fb-x',
    authDomain: 'auth--fb-x.firebaseapp.com',
    storageBucket: 'auth--fb-x.firebasestorage.app',
    measurementId: 'G-ZPRXFBBHZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJy2NIH4NEdy4E_YcLOlT4dC-knyuvpE',
    appId: '1:843619339586:android:5cc9a0097fabbed00b4cdb',
    messagingSenderId: '843619339586',
    projectId: 'auth--fb-x',
    storageBucket: 'auth--fb-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHoaK4rU_Hi31fwNwZjrAwan4eLvUidk',
    appId: '1:843619339586:ios:5e56d90fb848e9040b4cdb',
    messagingSenderId: '843619339586',
    projectId: 'auth--fb-x',
    storageBucket: 'auth--fb-x.firebasestorage.app',
    iosBundleId: 'com.example.firstPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnHoaK4rU_Hi31fwNwZjrAwan4eLvUidk',
    appId: '1:843619339586:ios:5e56d90fb848e9040b4cdb',
    messagingSenderId: '843619339586',
    projectId: 'auth--fb-x',
    storageBucket: 'auth--fb-x.firebasestorage.app',
    iosBundleId: 'com.example.firstPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7VC7Z9oCbt8y3virEqPsovvjzNvaXlXk',
    appId: '1:843619339586:web:b265a2af25e846230b4cdb',
    messagingSenderId: '843619339586',
    projectId: 'auth--fb-x',
    authDomain: 'auth--fb-x.firebaseapp.com',
    storageBucket: 'auth--fb-x.firebasestorage.app',
    measurementId: 'G-H5E2MX7YLY',
  );
}
